GET http://localhost:8080/list HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/1 HTTP/1.1

###

PUT http://localhost:8080/create HTTP/1.1
Content-Type: application/json

{
    "name": "Almaz", "phone": "0912668596", "email": "almu@eca.gov.et"
}

###

POST http://localhost:8080/update/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Torres"
}